'use client'

import { useState } from 'react'
import Link from 'next/link'
import { ArrowRight, Building2, Layers3, Plus } from 'lucide-react'
import { isOfferingSubscribable, isWealthManagerDetailsV2, representativeMandateNextOwnerLabel, type PortalCapability, type PortalInvestingRepresentativeMandate, type PortalOrganisation, type PortalOrganisationMandate, type PortalPageData, type PortalPath, type PortalProduct, type PortalSnapshot, type PortalSubscription } from '@/lib/portal/contracts'
import type { PlatformRelease } from '@/lib/platform-release'
import type { DashboardScope } from '@/lib/portal/dashboard'
import { getRoleDashboard } from '@/lib/portal/role-dashboards'
import { APPLICANT_CONTEXT, portalContextKey, portalScopeHref, type PortalOperatingContext } from '@/lib/portal/operating-context'
import { CommandFeedback, PortalCommandProvider, usePortalCommand } from './portal-client'
import { ProductForm } from './product-form'
import { PrivateDocument } from './onboarding-form'
import { PortalShell, type PortalNavigationKey } from './portal-shell'
import { DetailList, EmptyState, Field, Notice, Panel, Statistic, StatusBadge, dateLabel, money } from './portal-primitives'
import { ApplicationReview, InvestmentAccountPanel, IssuerOfferingReview, OfferingPackageEvidence, OfferingDocuments, ProductActions, ProductEligibilityPanel, ProductEligibilityReview, ProductFacts, ProductNarrative, ProductReview, SubscriptionCancel, SubscriptionForm, currentInvestorApplication } from './portal-workflows'
import { FundingOrderDetail, FundingWorkspace } from './funding-workflows'
import styles from './portal.module.css'

export function productManagementOrganisations(snapshot: PortalSnapshot, context?: PortalOperatingContext) {
  if (context?.mode === 'ROLE' && !['IssuerFundManager', 'OfferingManager'].includes(context.role)) return []
  return snapshot.organisations.filter(org => org.status === 'ACTIVE'
    && org.roles.some(role => ['IssuerFundManager', 'OfferingManager'].includes(role))
    && (!context || (context.mode === 'APPLICANT' ? org.authority_source === 'LEGACY_OWNER'
      : org.authority_source === 'NATIVE_BINDING' && org.native_organisation_id === context.organisationId && org.roles.includes(context.role))))
}

function permits(org: PortalOrganisation, command: PortalCapability, context?: PortalOperatingContext): boolean {
  return org.capabilities?.includes(command) ?? !context
}

function ProductCard({ product, operatingContext }: { product: PortalProduct; operatingContext?: PortalOperatingContext }) {
  return <article className={styles.productCard}>
    <div className={styles.productVisual} data-kind={product.terms.asset_type}>{product.terms.asset_type === 'FUND' ? <Layers3 aria-hidden="true" /> : <Building2 aria-hidden="true" />}<p>{product.terms.asset_type === 'FUND' ? 'Investment fund' : 'Real-estate investment'} · Fictional product</p></div>
    <div className={styles.productCardBody}><h2>{product.terms.name}</h2><p>{product.terms.summary}</p>
      <DetailList rows={[{ label: 'Unit price', value: money(product.terms.unit_price_minor) }, { label: 'Minimum investment', value: money((BigInt(product.terms.minimum_units) * BigInt(product.terms.unit_price_minor)).toString()) }, { label: 'Share class', value: product.terms.share_class }]} />
      <div className={styles.productCardFoot}><StatusBadge status={product.status} /><Link href={portalScopeHref('/portal/opportunities/detail', operatingContext, product.id)} className={styles.textLink}>View opportunity <span aria-hidden="true">↗</span></Link></div>
    </div>
  </article>
}

function ProductRegister({ products, canCreate, operatingContext }: { products: PortalProduct[]; canCreate: boolean; operatingContext?: PortalOperatingContext }) {
  return <Panel title="Product register" description="Fund and real-estate products share one workflow; submitted packages keep separate immutable references." action={canCreate ? <Link href={portalScopeHref('/portal/products/new', operatingContext)} className={styles.button}><Plus aria-hidden="true" />Create a product</Link> : undefined} flush>
    {products.length ? <div className={styles.tableWrap}><table className={styles.table}><thead><tr><th scope="col">Product</th><th scope="col">Template</th><th scope="col">Package</th><th scope="col">Status</th><th scope="col">Workspace</th></tr></thead>
      <tbody>{products.map(product => <tr key={product.id}><td><strong>{product.terms.name}</strong><small>{product.terms.issuer_name}</small></td><td>{product.terms.asset_type === 'FUND' ? 'Fund' : 'Real estate'}</td><td>{product.offering_package ? `Package ${product.offering_package.package_number}` : 'No current package'}<small>Workflow revision {product.revision}</small></td><td>{product.status === 'PUBLISHED' && !isOfferingSubscribable(product) ? 'Historical PUBLISHED state; opening not verified' : <StatusBadge status={product.status} />}</td><td><Link href={portalScopeHref('/portal/products/detail', operatingContext, product.id)}>Open product</Link></td></tr>)}</tbody>
    </table></div> : <EmptyState title={canCreate ? 'Build your first offering' : 'No products in this operating scope'} description={canCreate ? 'Start with the fund or real-estate template. The draft remains private until its exact terms have been independently reviewed and published.' : 'Only products covered by the current organisation and acting role appear here. No access is inferred from a similar organisation name.'} href={canCreate ? portalScopeHref('/portal/products/new', operatingContext) : undefined} action={canCreate ? 'Create a product' : undefined} />}
  </Panel>
}

export function SubscriptionOrders({ subscriptions, products, incoming, onSaved, operatingContext, funding }: {
  subscriptions: PortalSubscription[]; products: PortalProduct[]; incoming: boolean; onSaved: (snapshot: PortalSnapshot) => void; operatingContext?: PortalOperatingContext;
  funding?: PortalSnapshot['funding'];
}) {
  return <Panel title={incoming ? 'Incoming subscription orders' : 'Your subscription orders'} description="The investor and authorised issuer see the same saved order reference, accepted version and funding state." flush>
    {subscriptions.length ? <div className={styles.tableWrap}><table className={styles.table}><thead><tr><th scope="col">Product</th><th scope="col">Order reference</th><th scope="col">Investment account</th><th scope="col">Units</th><th scope="col">Instruction value</th><th scope="col">Status</th><th scope="col">Next action</th></tr></thead><tbody>
      {subscriptions.map(subscription => {
        const product = products.find(item => item.id === subscription.product_id)
        const recordedPackage = product?.offering_history?.find(item => item.id === subscription.offering_revision_id)
        const obligation = funding?.obligations.find(item => item.subscription_id === subscription.id)
        return <tr key={subscription.id}><td><strong>{subscription.product_name}</strong>{product ? <small>{product.terms.asset_type === 'FUND' ? 'Fund' : 'Real estate'}</small> : null}</td>
          <td><span className={styles.mono}>{subscription.id}</span><small>Recorded product workflow revision {subscription.product_revision} · {dateLabel(subscription.created_at)}</small><small>{subscription.offering_revision_id ? <>{recordedPackage?.origin === 'SUBMITTED' ? 'Submitted offering package' : recordedPackage ? 'Preserved historical terms snapshot; approval not inferred' : 'Terms package reference; origin unavailable'} <span className={styles.mono}>{subscription.offering_revision_id}</span></> : 'Historical instruction · no verified package reference'}</small><details><summary className={styles.textLink}>Accepted terms fingerprint</summary><p className={styles.mono}>{subscription.terms_hash}</p></details></td>
          <td>{subscription.investment_account_id ? <span className={styles.mono}>{subscription.investment_account_id}</span> : <span className={styles.muted}>Legacy instruction · account not linked</span>}</td>
          <td>{subscription.units}</td><td>{money(subscription.amount_minor)}</td><td><StatusBadge status={obligation && subscription.status === 'AWAITING_FUNDING' ? 'RESERVED' : subscription.status} />{obligation ? <div className={styles.sectionGap}><StatusBadge status={obligation.state} /><small>Funding state · not issued ownership</small></div> : null}</td>
          <td><div className={styles.stack}><Link href={portalScopeHref('/portal/orders/detail', operatingContext, subscription.id)}>Open funding record</Link>{incoming && product ? <Link href={portalScopeHref('/portal/products/detail', operatingContext, product.id)}>Open product and order book</Link> : null}
            {!funding ? <span className={styles.muted}>Funding records unavailable. Do not send funds or infer settlement.</span> : !obligation ? <span className={styles.muted}>No funding obligation has been opened. This reservation is not payment or issuance.</span> : null}
            {!incoming && subscription.status === 'AWAITING_FUNDING' ? <SubscriptionCancel id={subscription.id} onSaved={onSaved} canCancel={subscription.can_cancel === true} /> : subscription.status === 'CANCELLED' ? <span className={styles.muted}>Reservation cancelled; inspect the funding record for any unresolved payment evidence.</span> : null}
          </div></td>
        </tr>
      })}
    </tbody></table></div> : <EmptyState title={incoming ? 'No incoming orders in this scope' : 'No subscription orders yet'} description={incoming ? 'An eligible investor’s saved subscription appears here against the same published product. A product draft or reservation count is not a received payment.' : 'Accept a published offering’s exact terms from your active investment account. The saved instruction will appear here and in the authorised issuer’s order book.'} href={incoming ? undefined : portalScopeHref('/portal/opportunities', operatingContext)} action={incoming ? undefined : 'Explore opportunities'} />}
  </Panel>
}

function Opportunities({ products, snapshot, operatingContext }: { products: PortalProduct[]; snapshot: PortalSnapshot; operatingContext?: PortalOperatingContext }) {
  return <div className={styles.stack}>
    <Notice title="Read before you subscribe">Published offerings are shown for review; visibility does not establish investor eligibility. An active individual account and a current product-specific decision are required before the present individual subscription workflow can be used. No returns or liquidity are guaranteed.</Notice>
    {products.length ? <div className={styles.productGrid}>{products.map(product => <ProductCard key={product.id} product={product} operatingContext={operatingContext} />)}</div>
      : <Panel title="Published opportunities"><EmptyState title={currentInvestorApplication(snapshot) ? 'No published test offerings yet' : 'Prepare your investor access'} description={currentInvestorApplication(snapshot) ? 'An authorised issuer must obtain independent review and publish an offering before it appears here. Publication alone will not qualify an account.' : 'Complete your investor application and obtain a current independent approval. Product country and investor-classification rules still apply.'} href={currentInvestorApplication(snapshot) ? undefined : portalScopeHref('/portal/onboarding', operatingContext)} action={currentInvestorApplication(snapshot) ? undefined : 'Open my investor onboarding'} /></Panel>}
  </div>
}

function scopedMandates(snapshot: PortalSnapshot, operatingContext?: PortalOperatingContext): PortalOrganisationMandate[] {
  if (snapshot.mandate_queue_available !== true || operatingContext?.mode !== 'ROLE' || !['ComplianceOfficer', 'SuperAdmin'].includes(operatingContext.role)) return []
  if (operatingContext.role === 'ComplianceOfficer' && snapshot.actor.can_review !== true) return []
  return (snapshot.organisation_mandates ?? []).filter(item => item.reviewer_scope_organisation_id === operatingContext.organisationId)
}

function scopedEntityMandates(snapshot: PortalSnapshot, operatingContext?: PortalOperatingContext): PortalInvestingRepresentativeMandate[] {
  if (snapshot.entity_mandate_queue_available !== true || operatingContext?.mode !== 'ROLE' || !['ComplianceOfficer', 'SuperAdmin'].includes(operatingContext.role)) return []
  if (operatingContext.role === 'ComplianceOfficer' && snapshot.actor.can_review !== true) return []
  return (snapshot.investing_representative_mandates ?? []).filter(item => item.reviewer_scope_organisation_id === operatingContext.organisationId)
}

function EntityInvestingMandateQueue({ snapshot, operatingContext }: { snapshot: PortalSnapshot; operatingContext?: PortalOperatingContext }) {
  const cases = scopedEntityMandates(snapshot, operatingContext)
  const admin = operatingContext?.mode === 'ROLE' && operatingContext.role === 'SuperAdmin'
  return <Panel title={admin ? 'Entity investing mandates to apply' : 'Entity investing-representative review'} description="An entity investor account is the legal holder. Its representative requires a distinct case decision and application before limited account access is effective." flush>
    {snapshot.entity_mandate_queue_blocked_reason === 'MFA_REQUIRED' ? <Notice title="Authenticator required" tone="warning">Verify your staff authenticator before opening entity mandate cases. No case count or details are shown at this assurance level. <a href="/workspace/security">Open account security</a>.</Notice>
      : snapshot.entity_mandate_queue_blocked_reason === 'NOT_ADMITTED' ? <Notice title="Entity mandate review not admitted" tone="warning">This environment has not admitted the guarded review route. No cases or actions are shown.</Notice>
        : snapshot.entity_mandate_queue_available !== true || !Array.isArray(snapshot.investing_representative_mandates) ? <Notice title="Entity mandate queue unavailable" tone="warning">Refresh saved state before concluding that there are no appointment cases.</Notice>
          : cases.length ? <div className={styles.tableWrap}><table className={styles.table}><thead><tr><th scope="col">Entity investor</th><th scope="col">Scope</th><th scope="col">Status</th><th scope="col">Next owner</th><th scope="col">Action</th></tr></thead><tbody>{cases.map(item => <tr key={item.id}><td><strong>{item.entity_name}</strong><small className={styles.mono}>{item.id}</small></td><td>Account view; eligibility request reserved · zero transaction authority</td><td><StatusBadge status={item.status} /></td><td>{representativeMandateNextOwnerLabel(item.next_owner)}</td><td><Link href={portalScopeHref('/portal/compliance/detail', operatingContext, item.id)}>{admin && item.can_apply ? 'Apply reviewed mandate' : !admin && item.can_review ? 'Review appointment' : item.can_revoke ? 'Inspect and revoke' : 'Inspect case'}</Link></td></tr>)}</tbody></table></div>
            : <EmptyState title="No entity investing mandate cases in this scope" description="Only cases in this exact reviewer or application scope appear here. Investor admission does not automatically grant representation." />}
  </Panel>
}

function RepresentativeMandateQueue({ snapshot, operatingContext }: { snapshot: PortalSnapshot; operatingContext?: PortalOperatingContext }) {
  const mandates = scopedMandates(snapshot, operatingContext)
  const admin = operatingContext?.mode === 'ROLE' && operatingContext.role === 'SuperAdmin'
  return <Panel title={admin ? 'Approved representative mandates to apply' : 'Representative mandate review'} description="This queue governs each customer organisation's initial applying representative. Customer admission, independent appointment review and role application remain distinct saved decisions; adding other representatives is not supported here." flush>
    {snapshot.mandate_queue_blocked_reason === 'MFA_REQUIRED' ? <Notice title="Authenticator required" tone="warning">Complete authenticator verification for this staff operating context before checking the mandate queue. No case count or status is shown at this assurance level. <a href="/workspace/security">Open account security</a>.</Notice>
      : snapshot.mandate_queue_blocked_reason === 'NOT_ADMITTED' ? <Notice title="Mandate review route not admitted" tone="warning">This environment has not admitted the guarded representative-mandate review route. No cases or actions are shown.</Notice>
      : snapshot.mandate_queue_available !== true || !Array.isArray(snapshot.organisation_mandates) ? <Notice title="Mandate queue unavailable" tone="warning">Refresh saved state before concluding there are no appointment cases.</Notice>
      : mandates.length ? <div className={styles.tableWrap}><table className={styles.table}><thead><tr><th scope="col">Customer organisation</th><th scope="col">Role requested</th><th scope="col">Status</th><th scope="col">Next owner</th><th scope="col">Action</th></tr></thead><tbody>{mandates.map(item => <tr key={item.id}><td><strong>{item.organisation_name}</strong><small className={styles.mono}>{item.id}</small></td><td>Offering Manager</td><td><StatusBadge status={item.status} /></td><td>{representativeMandateNextOwnerLabel(item.next_owner)}</td><td><Link href={portalScopeHref('/portal/compliance/detail', operatingContext, item.id)}>{admin && item.can_apply && item.reviewer_user_id && item.reviewer_user_id !== snapshot.actor.id && item.applicant_user_id !== snapshot.actor.id ? 'Apply reviewed appointment' : !admin && item.can_review && item.applicant_user_id !== snapshot.actor.id ? 'Review appointment' : item.can_revoke ? 'Inspect and revoke' : 'Inspect status'}</Link></td></tr>)}</tbody></table></div>
      : <EmptyState title="No representative mandate cases in this scope" description="Only the exact reviewer or role-application scope returned by the backend appears here. Customer admission does not automatically create one." />}
  </Panel>
}

function RepresentativeMandateDecision({ mandate, snapshot, operatingContext, onSaved }: { mandate: PortalOrganisationMandate; snapshot: PortalSnapshot; operatingContext: PortalOperatingContext; onSaved: (snapshot: PortalSnapshot) => void }) {
  const [decision, setDecision] = useState<'APPROVED' | 'CHANGES_REQUIRED' | 'REJECTED'>('CHANGES_REQUIRED')
  const [notes, setNotes] = useState('')
  const [checks, setChecks] = useState({ appointment: false, evidence: false, scope: false })
  const [revokeReason, setRevokeReason] = useState('')
  const command = usePortalCommand(onSaved)
  const exactScope = operatingContext.mode === 'ROLE' && mandate.reviewer_scope_organisation_id === operatingContext.organisationId
  const compliance = exactScope && operatingContext.mode === 'ROLE' && operatingContext.role === 'ComplianceOfficer'
  const admin = exactScope && operatingContext.mode === 'ROLE' && operatingContext.role === 'SuperAdmin'
  const source = snapshot.applications.find(item => item.id === mandate.application_id && item.user_id === mandate.applicant_user_id && item.persona === 'WEALTH_MANAGER' && isWealthManagerDetailsV2(item.details) && item.admission_purpose === 'CUSTOMER_ORGANISATION_ADMISSION' && item.status === 'APPROVED' && item.revision === mandate.admission_revision && item.organisation_id === mandate.product_organisation_id)
  const approvalCurrent = mandate.admission_status === 'APPROVED' && mandate.admission_approved_until !== null && Date.parse(mandate.admission_approved_until) > Date.now()
    && Date.parse(mandate.requested_until) > Date.now()
  const canReview = compliance && snapshot.actor.can_review && mandate.can_review && mandate.status === 'SUBMITTED' && mandate.applicant_user_id !== snapshot.actor.id && approvalCurrent && Boolean(source)
  const canApply = admin && mandate.can_apply && mandate.status === 'APPROVED' && mandate.applicant_user_id !== snapshot.actor.id
    && mandate.reviewer_user_id !== null && mandate.reviewer_user_id !== snapshot.actor.id && approvalCurrent
  const canRevoke = (compliance && snapshot.actor.can_review || admin) && mandate.can_revoke && mandate.status === 'APPLIED' && mandate.applicant_user_id !== snapshot.actor.id
  return <div className={styles.wideGrid}><div className={styles.stack}>
    <Notice title="Manual test appointment evidence">This case concerns a fictional customer organisation. Its appointment reference is not live KYC, a product-compliance appointment or institutional signing authority.</Notice>
    <Panel title="Representative appointment case" action={<StatusBadge status={mandate.status} />}><DetailList rows={[{ label: 'Mandate reference', value: mandate.id }, { label: 'Customer organisation', value: mandate.organisation_name }, { label: 'Requested role', value: 'Offering Manager' }, { label: 'Case revision', value: mandate.revision }, { label: 'Admission revision', value: mandate.admission_revision }, { label: 'Requested expiry', value: dateLabel(mandate.requested_until) }, { label: 'Next responsible owner', value: representativeMandateNextOwnerLabel(mandate.next_owner) }, { label: 'Compliance reviewer', value: mandate.reviewer_user_id ?? 'Awaiting review' }, { label: 'Role applied by', value: mandate.applied_by_user_id ?? 'Not yet applied' }]} /><h3 className={styles.sectionGap}>Synthetic appointment evidence reference</h3><p className={styles.copy}>{mandate.evidence_reference}</p>{mandate.review_notes ? <><h3>Recorded decision rationale</h3><p className={styles.copy}>{mandate.review_notes}</p></> : null}</Panel>
    {source ? <Panel title="Approved customer admission source"><DetailList rows={[{ label: 'Representative', value: source.details.full_name }, { label: 'Customer organisation', value: source.details.company_name }, { label: 'Admission reference', value: source.id }, { label: 'Source evidence files', value: source.details.documents.length }]} /><Link href={portalScopeHref('/portal/compliance/detail', operatingContext, source.id)}>Inspect original admission and private evidence</Link></Panel> : compliance && mandate.status === 'SUBMITTED' ? <Notice title="Source admission unavailable" tone="warning">The approved source application is not in this review scope or no longer matches the appointment. No decision is available from this screen.</Notice> : null}
  </div><div className={styles.stack}>
    {canReview ? <Panel title="Independent compliance decision" description="Review the source admission, appointment evidence and exact organisation scope before deciding."><form className={styles.form} onSubmit={event => { event.preventDefault(); if (decision !== 'APPROVED' || Object.values(checks).every(Boolean)) void command.submit('review_representative_mandate', { mandate_id: mandate.id, expected_revision: mandate.revision, decision, notes, checks }) }}><fieldset className={styles.fieldset} disabled={command.busy || command.unknown}><legend>Appointment checks</legend>{([{ key: 'appointment', label: 'Synthetic representative appointment examined' }, { key: 'evidence', label: 'Source admission and appointment reference examined' }, { key: 'scope', label: 'Customer organisation and requested role scope confirmed' }] as const).map(item => <label key={item.key} className={styles.check}><input type="checkbox" checked={checks[item.key]} onChange={event => setChecks(current => ({ ...current, [item.key]: event.target.checked }))} />{item.label}</label>)}<Field label="Decision"><select value={decision} onChange={event => setDecision(event.target.value as typeof decision)}><option value="CHANGES_REQUIRED">Request changes</option><option value="APPROVED">Approve appointment for separate role application</option><option value="REJECTED">Reject appointment</option></select></Field><Field label="Decision rationale" hint="20 to 3000 characters. Explain the evidence and scope considered."><textarea required minLength={20} maxLength={3000} value={notes} onChange={event => setNotes(event.target.value)} /></Field><button className={styles.button} type="submit" disabled={decision === 'APPROVED' && !Object.values(checks).every(Boolean)}>Record appointment decision</button></fieldset></form></Panel> : null}
    {canApply ? <Panel title="Super Admin role application" description="A separate authorised Super Admin applies the already reviewed appointment. This creates only the exact Offering Manager organisation context."><button type="button" className={styles.button} disabled={command.busy || command.unknown} onClick={() => void command.submit('apply_representative_mandate', { mandate_id: mandate.id, expected_revision: mandate.revision })}>Apply reviewed Offering Manager mandate</button></Panel> : null}
    {canRevoke ? <Panel title="Revoke operating appointment" description="This protective action removes this exact mandate and operating assignment; it does not delete customer admission."><form className={styles.form} onSubmit={event => { event.preventDefault(); void command.submit('revoke_representative_mandate', { mandate_id: mandate.id, expected_revision: mandate.revision, reason: revokeReason }) }}><Field label="Revocation reason" hint="20 to 1000 characters. Explain why operating authority must stop."><textarea required minLength={20} maxLength={1000} value={revokeReason} disabled={command.busy || command.unknown} onChange={event => setRevokeReason(event.target.value)} /></Field><button className={styles.buttonSecondary} type="submit" disabled={command.busy || command.unknown}>Revoke this appointment</button></form></Panel> : null}
    {!canReview && !canApply && !canRevoke ? <Notice title="No action available">{mandate.applicant_user_id === snapshot.actor.id ? 'You cannot decide or apply your own appointment.' : 'This case is not awaiting an action under your current role and organisation scope.'}</Notice> : null}
    <CommandFeedback command={command} />
  </div></div>
}

function EntityInvestingMandateDecision({ mandate, snapshot, operatingContext, onSaved }: { mandate: PortalInvestingRepresentativeMandate; snapshot: PortalSnapshot; operatingContext: PortalOperatingContext; onSaved: (snapshot: PortalSnapshot) => void }) {
  const [decision, setDecision] = useState<'APPROVED' | 'CHANGES_REQUIRED' | 'REJECTED'>('CHANGES_REQUIRED')
  const [notes, setNotes] = useState('')
  const [checks, setChecks] = useState({ appointment: false, legal_entity: false, scope: false })
  const [revokeReason, setRevokeReason] = useState('')
  const command = usePortalCommand(onSaved)
  const exactScope = operatingContext.mode === 'ROLE' && mandate.reviewer_scope_organisation_id === operatingContext.organisationId
  const compliance = exactScope && operatingContext.mode === 'ROLE' && operatingContext.role === 'ComplianceOfficer' && snapshot.actor.can_review
  const admin = exactScope && operatingContext.mode === 'ROLE' && operatingContext.role === 'SuperAdmin'
  const source = snapshot.applications.find(item => item.id === mandate.application_id && item.user_id === mandate.applicant_user_id
    && item.persona === 'INVESTOR' && !isWealthManagerDetailsV2(item.details) && item.details.investor_type === 'ENTITY'
    && item.status === 'APPROVED' && item.revision === mandate.admission_revision && item.approved_until && Date.parse(item.approved_until) > Date.now())
  const appointmentDocument = source?.details.documents.find(document => document.id === mandate.appointment_document_id && document.kind === 'COMPANY')
  const admissionCurrent = mandate.admission_current_revision === mandate.admission_revision && Boolean(mandate.admission_approved_until)
    && Date.parse(mandate.admission_approved_until!) > Date.now() && Date.parse(mandate.requested_until) > Date.now()
  const independent = mandate.applicant_user_id !== snapshot.actor.id && mandate.representative_user_id !== snapshot.actor.id
  const canReview = compliance && mandate.can_review && mandate.status === 'SUBMITTED' && admissionCurrent && independent && Boolean(source && appointmentDocument)
  const canApply = admin && mandate.can_apply && mandate.status === 'APPROVED' && admissionCurrent && independent
    && Boolean(mandate.reviewer_user_id) && mandate.reviewer_user_id !== snapshot.actor.id
  const canRevoke = (compliance || admin) && mandate.can_revoke && mandate.status === 'APPLIED' && independent
  return <div className={styles.wideGrid}><div className={styles.stack}>
    <Notice title="Limited entity-investing mandate">This appointment currently enables account viewing only. Eligibility-request scope is reserved for a later guarded workflow; the transaction limit is zero. It does not approve a product, permit a subscription, move funds or grant wallet authority.</Notice>
    <Panel title="Entity representative case" action={<StatusBadge status={mandate.status} />}><DetailList rows={[{ label: 'Case reference', value: <span className={styles.mono}>{mandate.id}</span> }, { label: 'Legal entity', value: mandate.entity_name }, { label: 'Investment account', value: <span className={styles.mono}>{mandate.investment_account_id}</span> }, { label: 'Case revision', value: mandate.revision }, { label: 'Source admission revision', value: mandate.admission_revision }, { label: 'Requested expiry', value: dateLabel(mandate.requested_until) }, { label: 'Next responsible owner', value: representativeMandateNextOwnerLabel(mandate.next_owner) }, { label: 'Current scope', value: 'Account view; eligibility request reserved' }, { label: 'Transaction limit', value: 'Zero' }, { label: 'Compliance reviewer', value: mandate.reviewer_user_id ?? 'Awaiting review' }, { label: 'Applied by', value: mandate.applied_by_user_id ?? 'Not yet applied' }]} /><h3 className={styles.sectionGap}>Appointment evidence reference</h3><p className={styles.copy}>{mandate.evidence_reference}</p>{mandate.review_notes ? <><h3>Recorded review rationale</h3><p className={styles.copy}>{mandate.review_notes}</p></> : null}</Panel>
    {source && appointmentDocument ? <Panel title="Approved entity admission and appointment evidence"><DetailList rows={[{ label: 'Source application', value: <span className={styles.mono}>{source.id}</span> }, { label: 'Entity name', value: source.details.company_name }, { label: 'Registration reference', value: source.details.registration_reference }, { label: 'Representative', value: source.details.full_name }, { label: 'Admission expiry', value: dateLabel(source.approved_until) }, { label: 'Appointment document', value: appointmentDocument.title }]} /><div className={styles.sectionGap}><PrivateDocument document={appointmentDocument} /></div></Panel>
      : compliance && mandate.status === 'SUBMITTED' ? <Notice title="Source appointment evidence unavailable" tone="warning">The exact approved entity application or bound COMPANY document is not available in this review scope. Approval is disabled until it can be inspected.</Notice> : null}
  </div><div className={styles.stack}>
    {compliance ? <Panel title="Independent representative decision" description="The server rechecks current admission, document binding, MFA, review scope and principal separation."><CommandFeedback command={command} />
      {canReview ? <form className={styles.form} onSubmit={event => { event.preventDefault(); if (decision !== 'APPROVED' || Object.values(checks).every(Boolean)) void command.submit('review_investing_representative_mandate', { mandate_id: mandate.id, expected_revision: mandate.revision, decision, notes, checks }) }}><fieldset className={styles.fieldset} disabled={command.busy || command.unknown}><legend>Evidence checks</legend>{([
        { key: 'appointment', label: 'Bound COMPANY document and appointment evidence inspected' },
        { key: 'legal_entity', label: 'Legal entity, ownership and source admission checked' },
        { key: 'scope', label: 'Account-view scope, reserved eligibility-request scope, zero transaction limit and expiry checked' },
      ] as const).map(item => <label key={item.key} className={styles.check}><input type="checkbox" checked={checks[item.key]} onChange={event => setChecks(current => ({ ...current, [item.key]: event.target.checked }))} />{item.label}</label>)}<Field label="Decision"><select value={decision} onChange={event => setDecision(event.target.value as typeof decision)}><option value="CHANGES_REQUIRED">Request changes</option><option value="APPROVED">Approve for separate Super Admin application</option><option value="REJECTED">Reject appointment</option></select></Field><Field label="Decision rationale" hint="20 to 3,000 characters explaining the evidence and scope considered."><textarea required minLength={20} maxLength={3000} value={notes} onChange={event => setNotes(event.target.value)} /></Field><button type="submit" className={styles.button} disabled={decision === 'APPROVED' && !Object.values(checks).every(Boolean)}>Record entity mandate decision</button></fieldset></form>
        : <Notice title="Decision unavailable">{!independent ? 'You cannot review or apply your own representative case.' : mandate.status !== 'SUBMITTED' ? 'This case is not awaiting a Compliance decision.' : !admissionCurrent ? 'The admission or requested expiry is no longer current.' : 'Current independent review authority and the exact source evidence are required.'}</Notice>}
    </Panel> : null}
    {canApply ? <Panel title="Apply reviewed entity mandate" description="A separately authorised Super Admin activates only the reviewed limited scope."><CommandFeedback command={command} /><button type="button" className={styles.button} disabled={command.busy || command.unknown} onClick={() => void command.submit('apply_investing_representative_mandate', { mandate_id: mandate.id, expected_revision: mandate.revision })}>Apply account-view mandate</button></Panel> : null}
    {canRevoke ? <Panel title="Revoke entity mandate" description="Revocation ends the representative's effective account access."><CommandFeedback command={command} /><form className={styles.form} onSubmit={event => { event.preventDefault(); if (revokeReason.trim().length >= 20) void command.submit('revoke_investing_representative_mandate', { mandate_id: mandate.id, expected_revision: mandate.revision, reason: revokeReason.trim() }) }}><Field label="Revocation reason" hint="20 to 1,000 characters. Record why the appointment is ending."><textarea required minLength={20} maxLength={1000} value={revokeReason} onChange={event => setRevokeReason(event.target.value)} /></Field><button type="submit" className={styles.button} disabled={command.busy || command.unknown || revokeReason.trim().length < 20}>Revoke account-view mandate</button></form></Panel> : null}
  </div></div>
}

function ComplianceQueue({ snapshot, operatingContext }: { snapshot: PortalSnapshot; operatingContext?: PortalOperatingContext }) {
  const applications = snapshot.applications.filter(item => item.status === 'SUBMITTED')
  const products = snapshot.products.filter(item => item.status === 'IN_REVIEW' && item.offering_package?.compliance_status === 'PENDING')
  const eligibilityUnavailable = !Array.isArray(snapshot.product_eligibility)
  const eligibilityCases = Array.isArray(snapshot.product_eligibility) ? snapshot.product_eligibility.filter(item => (item.status === 'SUBMITTED' || item.status === 'APPROVED' && item.can_revoke === true)
    && snapshot.products.some(product => product.id === item.product_id && product.organisation_id === item.organisation_id)) : []
  return <div className={styles.stack}>
    <div className={styles.statGrid}><Statistic label="Client applications" value={applications.length} hint="Submitted evidence packages in this review scope" /><Statistic label="Offering reviews" value={products.length} hint="Immutable offering packages awaiting Compliance" /><Statistic label="Product eligibility actions" value={eligibilityUnavailable ? 'Unavailable' : eligibilityCases.length} hint="Submitted cases and revocable approvals in this review scope" /><Statistic label="Representative mandates" value={snapshot.mandate_queue_available === true && Array.isArray(snapshot.organisation_mandates) ? scopedMandates(snapshot, operatingContext).filter(item => item.can_review || item.can_revoke).length : 'Unavailable'} hint="Independent customer-role appointment cases" /><Statistic label="Entity investing mandates" value={snapshot.entity_mandate_queue_available === true && Array.isArray(snapshot.investing_representative_mandates) ? scopedEntityMandates(snapshot, operatingContext).filter(item => item.can_review || item.can_revoke).length : 'Unavailable'} hint="Separate legal-holder representative cases" /><Statistic label="Review provider" value="Manual" hint="Rehearsal evidence review · no live KYC-provider claim" /></div>
    <RepresentativeMandateQueue snapshot={snapshot} operatingContext={operatingContext} />
    <EntityInvestingMandateQueue snapshot={snapshot} operatingContext={operatingContext} />
    <Panel title="Compliance work queue" description="Open a saved case, review its evidence and record an independent decision." flush>
      {eligibilityUnavailable ? <Notice title="Product eligibility records are unavailable" tone="warning">Refresh saved state before concluding that no product eligibility cases need review.</Notice> : null}
      {applications.length || products.length || eligibilityCases.length ? <div className={styles.tableWrap}><table className={styles.table}><thead><tr><th scope="col">Case</th><th scope="col">Review type</th><th scope="col">Version</th><th scope="col">Independence</th><th scope="col">Action</th></tr></thead><tbody>
        {applications.map(application => <tr key={application.id}><td><strong>{application.persona === 'WEALTH_MANAGER' ? application.details.company_name || 'Customer organisation application' : application.details.full_name}</strong>{application.persona === 'WEALTH_MANAGER' ? <small>Representative: {application.details.full_name}</small> : null}<small>Submitted {dateLabel(application.submitted_at)}</small><small className={styles.mono}>{application.id}</small></td><td>{application.persona === 'INVESTOR' ? 'Investor admission' : application.admission_purpose === 'LEGACY_REHEARSAL' ? 'Historical rehearsal relationship' : 'Customer organisation admission'}</td><td>{application.revision}</td><td>{application.user_id === snapshot.actor.id ? 'Another reviewer required' : 'Backend rechecks independent authority'}</td><td><Link href={portalScopeHref('/portal/compliance/detail', operatingContext, application.id)}>Review case</Link></td></tr>)}
        {products.map(product => <tr key={product.id}><td><strong>{product.terms.name}</strong><small>{product.terms.asset_type === 'FUND' ? 'Fund' : 'Real estate'} · {product.terms.issuer_name}</small></td><td>Offering Compliance</td><td>{product.offering_package ? `Package ${product.offering_package.package_number}` : 'No current package'}</td><td>{product.created_by === snapshot.actor.id ? 'Another reviewer required' : 'Backend rechecks independent authority'}</td><td><Link href={portalScopeHref('/portal/compliance/detail', operatingContext, product.id)}>Review offering</Link></td></tr>)}
        {eligibilityCases.map(item => <tr key={item.id}><td><strong>{item.product_name ?? snapshot.products.find(product => product.id === item.product_id)?.terms.name ?? 'Published offering'}</strong><small>Investment account {item.investment_account_id}</small><small>Submitted {dateLabel(item.submitted_at)}</small><small className={styles.mono}>{item.id}</small></td><td>Product eligibility · {item.status === 'APPROVED' ? 'revocation available' : 'review requested'}</td><td>{item.revision}</td><td>{item.holder_user_id === snapshot.actor.id ? 'Another reviewer required' : 'Backend rechecks independent authority'}</td><td><Link href={portalScopeHref('/portal/compliance/detail', operatingContext, item.id)}>{item.status === 'APPROVED' ? 'Inspect approval' : 'Review eligibility'}</Link></td></tr>)}
      </tbody></table></div> : eligibilityUnavailable ? null : <EmptyState title="No cases are waiting for review" description="Submitted customer, offering and product eligibility cases appear here within your appointed review scope. Nothing is approved automatically." />}
    </Panel>
  </div>
}

function RoleHelp({ operatingContext }: { operatingContext?: PortalOperatingContext }) {
  const role = operatingContext?.mode === 'ROLE' ? getRoleDashboard(operatingContext.role) : undefined
  if (!role) return null
  return <details className={styles.panel}><summary className={styles.panelHeader}>Role, hand-offs and signing guidance</summary><div className={styles.panelBody}><h2>{role.title}</h2><p className={styles.copy}>{role.description}</p><ul>{role.responsibilities.map(item => <li key={item}>{item}</li>)}</ul><h3>Working with other roles</h3><ul>{role.handoffs.map(item => <li key={item}>{item}</li>)}</ul><h3>Wallet and signing</h3><p className={styles.copy}>{role.walletGuidance}</p><h3>Authority boundary</h3><p className={styles.copy}>{role.authorityBoundary}</p></div></details>
}

const PAGE: Record<PortalPath, { title: string; eyebrow: string; description: string; active: PortalNavigationKey }> = {
  '/portal': { title: 'Your BlockXOne workspace.', eyebrow: 'Welcome to BlockXOne', description: 'Your saved relationships, assignments and work queues are kept separate.', active: 'overview' },
  '/portal/onboarding': { title: 'Start with your identity.', eyebrow: 'Client onboarding', description: 'Apply as an investor or wealth manager. Your information, evidence and review decision stay connected.', active: 'onboarding' },
  '/portal/products': { title: 'Products & offerings.', eyebrow: 'Product management', description: 'Structure fund and real-estate offerings and follow their saved subscription orders.', active: 'products' },
  '/portal/products/new': { title: 'Structure a new product.', eyebrow: 'Product management / new product', description: 'Define the issuer, asset, economics and investor disclosures before submitting a single version for review.', active: 'products' },
  '/portal/products/detail': { title: 'Product workspace.', eyebrow: 'Product management / offering', description: 'One product record connects terms, independent review, publication and incoming orders.', active: 'products' },
  '/portal/compliance': { title: 'Review with context.', eyebrow: 'Compliance work queue', description: 'Review saved applicant evidence and offering terms within your appointed scope.', active: 'compliance' },
  '/portal/compliance/detail': { title: 'Review case.', eyebrow: 'Compliance / case review', description: 'Read the source evidence and record a reasoned decision against the current revision.', active: 'compliance' },
  '/portal/opportunities': { title: 'Explore investment opportunities.', eyebrow: 'Investor marketplace', description: 'Read published product terms and disclosures before submitting a subscription instruction.', active: 'opportunities' },
  '/portal/opportunities/detail': { title: 'Investment opportunity.', eyebrow: 'Investor marketplace / offering', description: 'Review the mandate, unit economics, eligibility rules and exact offering documents.', active: 'opportunities' },
  '/portal/portfolio': { title: 'Your investment account and instructions.', eyebrow: 'Investment account / orders', description: 'Open or review your investment account and track the same subscription orders seen by the authorised issuer. Reserved units are not funded ownership.', active: 'portfolio' },
  '/portal/orders/detail': { title: 'Subscription funding record.', eyebrow: 'Subscription / funding and reconciliation', description: 'Follow the same accepted order through funding instructions, verified evidence and independent accounting.', active: 'overview' },
}

type PortalScreenProps = { data: PortalPageData; view: PortalPath; id?: string; operatingContext?: PortalOperatingContext; release?: PlatformRelease; scope?: DashboardScope; scopes?: DashboardScope[] }

export function PortalScreen(props: PortalScreenProps) {
  // A role/organisation change must not retain another context's client snapshot.
  return <OperatingPortalScreen key={`${props.data.user.id}:${props.release?.environment ?? 'UNSPECIFIED'}:${portalContextKey(props.operatingContext ?? APPLICANT_CONTEXT)}:${props.view}:${props.id ?? ''}`} {...props} />
}

function OperatingPortalScreen({ data, view, id, operatingContext, release, scope, scopes }: PortalScreenProps) {
  const [snapshot, setSnapshot] = useState(data.snapshot)
  const organisations = productManagementOrganisations(snapshot, operatingContext)
  const createOrganisations = organisations.filter(org => permits(org, 'create_product', operatingContext))
  const canReview = snapshot.actor.can_review && operatingContext?.mode === 'ROLE' && operatingContext.role === 'ComplianceOfficer'
  const role = operatingContext?.mode === 'ROLE' ? operatingContext.role : undefined
  const ownApplications = snapshot.applications.filter(item => item.user_id === snapshot.actor.id)
  // An applicant route is not an Investor role. Only an explicit investor
  // application (or a server-returned Investor operating role) opens these
  // surfaces; a wealth-manager-only relationship must not fall into them.
  const hasInvestorCapacity = ownApplications.some(item => item.persona === 'INVESTOR')
  const hasCurrentIndividualInvestor = ownApplications.some(item => item.persona === 'INVESTOR' && !isWealthManagerDetailsV2(item.details) && item.details.investor_type === 'INDIVIDUAL'
    && item.status === 'APPROVED' && Boolean(item.approved_until) && Date.parse(item.approved_until!) > Date.now())
  const hasEntityInvestorCapacity = ownApplications.some(item => item.persona === 'INVESTOR' && !isWealthManagerDetailsV2(item.details) && item.details.investor_type === 'ENTITY')
  const hasEntityAccountView = (snapshot.entity_investment_accounts ?? []).some(item => item.can_view)
  const entityOnly = !hasCurrentIndividualInvestor && (hasEntityInvestorCapacity || hasEntityAccountView)
  const canInvest = role === 'Investor' || (operatingContext?.mode !== 'ROLE' && (hasInvestorCapacity || hasEntityAccountView))
  const capabilities = { manageProducts: organisations.length > 0, reviewCompliance: canReview, invest: canInvest }
  const ownSubscriptions = snapshot.subscriptions.filter(item => item.investor_id === snapshot.actor.id)
  const managedProducts = snapshot.products.filter(product => organisations.some(org => org.id === product.organisation_id))
  const orderOrganisations = organisations.filter(org => permits(org, 'read_orders', operatingContext))
  const incomingSubscriptions = snapshot.subscriptions.filter(item => orderOrganisations.some(org => org.id === item.organisation_id) && managedProducts.some(product => product.id === item.product_id))
  const published = snapshot.products.filter(isOfferingSubscribable)
  const detailProducts = view === '/portal/products/detail' ? managedProducts : view === '/portal/opportunities/detail' ? published : canReview ? snapshot.products : []
  const selected = id ? detailProducts.find(product => product.id === id) : undefined
  const selectedApplication = id && canReview ? snapshot.applications.find(application => application.id === id) : undefined
  const selectedEligibility = id && canReview && Array.isArray(snapshot.product_eligibility) ? snapshot.product_eligibility.find(item => item.id === id
    && snapshot.products.some(product => product.id === item.product_id && product.organisation_id === item.organisation_id)) : undefined
  const selectedMandate = id ? scopedMandates(snapshot, operatingContext).find(item => item.id === id) : undefined
  const selectedEntityMandate = id ? scopedEntityMandates(snapshot, operatingContext).find(item => item.id === id) : undefined
  const reviewSnapshot = canReview ? snapshot : { ...snapshot, actor: { ...snapshot.actor, can_review: false } }
  const config = PAGE[view]
  const roleTitle = role === 'Investor' ? 'Your investments and orders.' : role === 'OfferingManager' || role === 'IssuerFundManager' ? 'Your products and incoming orders.' : role === 'ComplianceOfficer' ? 'Your compliance work queue.' : role === 'SuperAdmin' ? 'Your platform administration queue.' : role === 'TreasuryOperator' ? 'Your funding operations.' : role === 'FinancialController' ? 'Your independent reconciliation queue.' : undefined
  const title = selected && ['/portal/products/detail', '/portal/opportunities/detail'].includes(view) ? selected.terms.name : selectedApplication && view === '/portal/compliance/detail' ? selectedApplication.details.full_name : selectedEligibility && view === '/portal/compliance/detail' ? `Eligibility: ${selectedEligibility.product_name ?? snapshot.products.find(product => product.id === selectedEligibility.product_id)?.terms.name ?? 'offering'}` : selectedEntityMandate && view === '/portal/compliance/detail' ? `Entity mandate: ${selectedEntityMandate.entity_name}` : selectedMandate && view === '/portal/compliance/detail' ? `Representative appointment: ${selectedMandate.organisation_name}` : view === '/portal' && roleTitle ? roleTitle : config.title
  const href = (path: PortalPath, recordId?: string) => portalScopeHref(path, operatingContext, recordId)
  const parentPath: PortalPath = config.active === 'products' ? '/portal/products' : config.active === 'compliance' ? '/portal/compliance' : config.active === 'portfolio' ? '/portal/portfolio' : config.active === 'onboarding' ? '/portal/onboarding' : '/portal/opportunities'
  const breadcrumbs = view === '/portal' ? [] : view === '/portal/orders/detail' ? [{ label: 'My operating workspace', href: href('/portal') }, { label: 'Subscription funding' }] : [{ label: config.active === 'products' ? 'Products & offerings' : config.active === 'compliance' ? 'Compliance' : config.active === 'opportunities' ? 'Opportunities' : config.active === 'portfolio' ? 'My orders' : 'My onboarding', href: view.includes('/detail') || view.endsWith('/new') ? href(parentPath) : undefined }, ...(view.includes('/detail') ? [{ label: selected?.terms.name || selectedApplication?.details.full_name || (selectedEntityMandate ? 'Entity investing mandate' : selectedMandate ? 'Representative appointment' : selectedEligibility ? 'Product eligibility case' : 'Details') }] : view.endsWith('/new') ? [{ label: 'New product' }] : [])]

  function unavailable() { return <Panel title="Record unavailable"><EmptyState title="This record is not available in your current operating scope" description="It may have changed or belong to another organisation. No access is granted by a shared URL." href={href('/portal')} action="Return to dashboard" /></Panel> }
  const fundingOutstanding = (subscription: PortalSubscription) => subscription.status === 'AWAITING_FUNDING' && !snapshot.funding?.obligations.some(item => item.subscription_id === subscription.id && item.state === 'RECONCILED')
  function productStats() { return <div className={styles.statGrid}><Statistic label="Products in your scope" value={managedProducts.length} hint="Current organisation and acting role" /><Statistic label="Awaiting review" value={managedProducts.filter(product => product.status === 'IN_REVIEW').length} hint="Independent decision required" /><Statistic label="Incoming orders awaiting funding" value={orderOrganisations.length ? incomingSubscriptions.filter(fundingOutstanding).length : 'Unavailable'} hint={orderOrganisations.length ? 'Saved instructions, not settled investments' : 'Order-reading authority is not available in this scope'} /></div> }
  function orderStats() {
    const pending = ownSubscriptions.filter(fundingOutstanding)
    const amount = pending.reduce((sum, subscription) => sum + BigInt(subscription.amount_minor), 0n).toString()
    return <div className={styles.statGrid}><Statistic label="Subscription instructions" value={ownSubscriptions.length} hint="Your saved instructions" /><Statistic label="Awaiting funding" value={pending.length} hint="Reserved, not issued" /><Statistic label="Requested subscription amount" value={money(amount)} hint="Awaiting-funding instructions only" /></div>
  }
  function investorWork() {
    return entityOnly
      ? <div className={styles.stack}><InvestmentAccountPanel snapshot={snapshot} onSaved={setSnapshot} operatingContext={operatingContext} /><Panel title="Entity offering access" description="A legal-holder account and limited representative appointment do not create a product qualification or order."><Notice title="Entity orders are not enabled">The product-specific entity eligibility, subscription, settlement and ownership workflows are not yet available. Existing individual orders, if any, are separate records.</Notice></Panel></div>
      : <div className={styles.stack}>{orderStats()}<InvestmentAccountPanel snapshot={snapshot} onSaved={setSnapshot} operatingContext={operatingContext} /><SubscriptionOrders subscriptions={ownSubscriptions} products={snapshot.products} incoming={false} onSaved={setSnapshot} operatingContext={operatingContext} funding={snapshot.funding} /><Panel title="Investment opportunities" description="Explore the published products available to your approved relationship."><Opportunities products={published} snapshot={snapshot} operatingContext={operatingContext} /></Panel></div>
  }
  function productWork() {
    const issuerCases = role === 'IssuerFundManager' ? managedProducts.filter(product => product.offering_package?.can_review_issuer === true && product.allowed_actions?.includes('review_offering_issuer')) : []
    return <div className={styles.stack}>{productStats()}{role === 'IssuerFundManager' ? <Panel title="Packages awaiting your issuer decision" description="Only server-authorised packages appear; preparing a product does not grant the right to approve it.">{issuerCases.length ? <ul>{issuerCases.map(product => <li key={product.id}><Link href={href('/portal/products/detail', product.id)} className={styles.textLink}>{product.terms.name} · package {product.offering_package?.package_number}</Link></li>)}</ul> : <p className={styles.muted}>No package is currently assigned to this issuer context for a decision. An issuer appointment is separate from a manager relationship.</p>}</Panel> : null}<ProductRegister products={managedProducts} canCreate={createOrganisations.length > 0} operatingContext={operatingContext} />{orderOrganisations.length ? <SubscriptionOrders subscriptions={incomingSubscriptions} products={managedProducts} incoming onSaved={setSnapshot} operatingContext={operatingContext} funding={snapshot.funding} /> : <Notice title="Order access unavailable">Your current mandate does not provide an incoming-order view. This is not an empty order book or a zero balance.</Notice>}</div>
  }
  function content() {
    if (view === '/portal/orders/detail') {
      const subscription = snapshot.subscriptions.find(item => item.id === id)
      const context = operatingContext ?? APPLICANT_CONTEXT
      const allowedRole = context.mode === 'APPLICANT' || ['Investor', 'OfferingManager', 'IssuerFundManager', 'TreasuryOperator', 'FinancialController'].includes(context.role)
      const owned = subscription?.investor_id === snapshot.actor.id && (context.mode === 'APPLICANT' || context.role === 'Investor')
      const assigned = subscription && context.mode === 'ROLE' && ['OfferingManager', 'IssuerFundManager', 'TreasuryOperator', 'FinancialController'].includes(context.role) && snapshot.organisations.some(org => org.id === subscription.organisation_id && org.status === 'ACTIVE' && org.authority_source === 'NATIVE_BINDING' && org.native_organisation_id === context.organisationId && org.roles.includes(context.role))
      const legacyOwner = subscription && context.mode === 'APPLICANT' && orderOrganisations.some(org => org.id === subscription.organisation_id)
      return subscription && allowedRole && (owned || assigned || legacyOwner) ? <FundingOrderDetail subscription={subscription} snapshot={snapshot} operatingContext={context} onSaved={setSnapshot} /> : unavailable()
    }
    if (view === '/portal/onboarding') return <Link href="/portal/onboarding?mode=applicant" className={styles.button}>Open my application capacities</Link>
    if (view === '/portal/products/new') return createOrganisations.length ? <ProductForm organisations={createOrganisations} onSaved={setSnapshot} operatingContext={operatingContext} /> : <Panel title="Product access"><EmptyState title="A scoped product-creation mandate is required" description="An organisation name or another role assignment does not grant product-creation access in this operating scope." href={href('/portal')} action="Return to dashboard" /></Panel>
    if (view === '/portal/products') return productWork()
    if (view === '/portal/products/detail') {
      if (!selected) return unavailable()
      const organisation = organisations.find(org => org.id === selected.organisation_id)
      const canEdit = organisation && permits(organisation, 'save_product', operatingContext)
      return <div className={styles.stack}><div className={styles.wideGrid}><div className={styles.stack}><ProductFacts product={selected} /><OfferingPackageEvidence product={selected} showIssuerRationale={Boolean(canEdit)} /><ProductNarrative product={selected} /><OfferingDocuments product={selected} /></div><div className={styles.stack}>{organisation ? <ProductActions product={selected} onSaved={setSnapshot} availableCommands={organisation.capabilities ?? (operatingContext ? [] : undefined)} /> : <Notice title="Read-only product access">No product-management mandate is available for this organisation.</Notice>}{role === 'IssuerFundManager' && selected.offering_package && selected.status === 'IN_REVIEW' ? <IssuerOfferingReview product={selected} snapshot={snapshot} onSaved={setSnapshot} /> : null}</div></div>{canEdit && ['DRAFT', 'CHANGES_REQUIRED'].includes(selected.status) ? <ProductForm key={`${selected.id}-${selected.revision}`} organisations={organisations.filter(org => permits(org, 'save_product', operatingContext))} product={selected} onSaved={setSnapshot} operatingContext={operatingContext} /> : null}{organisation && permits(organisation, 'read_orders', operatingContext) ? <SubscriptionOrders subscriptions={incomingSubscriptions.filter(item => item.product_id === selected.id)} products={[selected]} incoming onSaved={setSnapshot} operatingContext={operatingContext} funding={snapshot.funding} /> : <Notice title="Order access unavailable">This product’s incoming-order book is not available under your current mandate.</Notice>}</div>
    }
    if (view === '/portal/compliance') return canReview ? <ComplianceQueue snapshot={reviewSnapshot} operatingContext={operatingContext} /> : role === 'SuperAdmin' ? <div className={styles.stack}><RepresentativeMandateQueue snapshot={snapshot} operatingContext={operatingContext} /><EntityInvestingMandateQueue snapshot={snapshot} operatingContext={operatingContext} /></div> : unavailable()
    if (view === '/portal/compliance/detail') {
      if (selectedEntityMandate) return <EntityInvestingMandateDecision key={`${selectedEntityMandate.id}-${selectedEntityMandate.revision}`} mandate={selectedEntityMandate} snapshot={snapshot} operatingContext={operatingContext ?? APPLICANT_CONTEXT} onSaved={setSnapshot} />
      if (selectedMandate) return <RepresentativeMandateDecision key={`${selectedMandate.id}-${selectedMandate.revision}`} mandate={selectedMandate} snapshot={snapshot} operatingContext={operatingContext ?? APPLICANT_CONTEXT} onSaved={setSnapshot} />
      if (!canReview) return unavailable()
      return selectedApplication ? <ApplicationReview key={`${selectedApplication.id}-${selectedApplication.revision}`} application={selectedApplication} snapshot={reviewSnapshot} onSaved={setSnapshot} /> : selectedEligibility ? <ProductEligibilityReview key={`${selectedEligibility.id}-${selectedEligibility.revision}`} eligibility={selectedEligibility} product={snapshot.products.find(product => product.id === selectedEligibility.product_id)} snapshot={reviewSnapshot} onSaved={setSnapshot} /> : selected ? <ProductReview key={`${selected.id}-${selected.revision}`} product={selected} snapshot={reviewSnapshot} onSaved={setSnapshot} /> : unavailable()
    }
    if (view === '/portal/opportunities') return canInvest ? entityOnly ? <Panel title="Entity offering access"><Notice title="Entity product flow not enabled">Published terms may be reviewed later, but this release does not accept entity-specific product eligibility or subscription instructions. Your entity account and appointment remain visible in <Link href={href('/portal/portfolio')} className={styles.textLink}>your investment workspace</Link>.</Notice></Panel> : <Opportunities products={published} snapshot={snapshot} operatingContext={operatingContext} /> : unavailable()
    if (view === '/portal/opportunities/detail') return canInvest && selected && isOfferingSubscribable(selected) ? <div className={styles.wideGrid}><div className={styles.stack}><Notice title="Fictional test offering">{selected.terms.summary}</Notice><ProductFacts product={selected} /><OfferingPackageEvidence product={selected} /><ProductNarrative product={selected} /><OfferingDocuments product={selected} /></div><div className={styles.stack}>{entityOnly ? <Notice title="Entity subscriptions are unavailable" tone="warning">An entity account and appointment are not product eligibility or transaction authority. This offering cannot receive an entity order through the current workflow.</Notice> : <><ProductEligibilityPanel product={selected} snapshot={snapshot} onSaved={setSnapshot} operatingContext={operatingContext} /><SubscriptionForm product={selected} snapshot={snapshot} onSaved={setSnapshot} operatingContext={operatingContext} /></>}</div></div> : unavailable()
    if (view === '/portal/portfolio') return canInvest ? entityOnly ? <InvestmentAccountPanel snapshot={snapshot} onSaved={setSnapshot} operatingContext={operatingContext} /> : <div className={styles.stack}>{orderStats()}<InvestmentAccountPanel snapshot={snapshot} onSaved={setSnapshot} operatingContext={operatingContext} /><Notice title="Reservations are not holdings">These are subscription instructions with reserved units. A reservation does not confirm funding, token ownership or investment performance.</Notice><SubscriptionOrders subscriptions={ownSubscriptions} products={snapshot.products} incoming={false} onSaved={setSnapshot} operatingContext={operatingContext} funding={snapshot.funding} /></div> : unavailable()
    if (role === 'ComplianceOfficer') return canReview ? <ComplianceQueue snapshot={reviewSnapshot} operatingContext={operatingContext} /> : unavailable()
    if (role === 'OfferingManager' || role === 'IssuerFundManager') return productWork()
    if (role === 'Investor') return investorWork()
    if ((role === 'TreasuryOperator' || role === 'FinancialController') && operatingContext) return <FundingWorkspace snapshot={snapshot} operatingContext={operatingContext} onSaved={setSnapshot} />
    if (role === 'SuperAdmin' && operatingContext?.mode === 'ROLE') return <div className={styles.stack}><RepresentativeMandateQueue snapshot={snapshot} operatingContext={operatingContext} /><EntityInvestingMandateQueue snapshot={snapshot} operatingContext={operatingContext} /><Panel title="Separate gated administration service" description="The mandate queues above are connected appointment handoffs. The broader administration service requires its own configured authority root and may be unavailable in this environment. Business and wallet-signing powers remain separate."><div className={styles.actions}><Link href={`/workspace/administration?organisation=${encodeURIComponent(operatingContext.organisationId)}`} className={styles.buttonSecondary}>Open gated administration, if configured</Link><a href="/workspace/security" className={styles.buttonSecondary}>Account security</a></div></Panel></div>
    if (role) return <Panel title="Operational records unavailable"><EmptyState title="No connected operating queue is available for this role" description="This release does not manufacture settlement, register or token operations. Your assigned organisation and sign-in remain unchanged." /></Panel>
    if (capabilities.manageProducts) return <div className={styles.stack}><Notice title="Approved applicant product relationship">These products use your existing approved owner relationship. This is not a native organisation role assignment.</Notice>{productWork()}</div>
    return <div className={styles.stack}><section className={styles.hero}><div><p className={styles.eyebrow}>Your BlockXOne relationship</p><h2>{entityOnly ? hasEntityAccountView ? 'View your represented entity account.' : 'Follow your entity admission and appointment.' : hasInvestorCapacity ? currentInvestorApplication(snapshot) ? 'Review opportunities. Track every instruction.' : 'Complete your investor onboarding.' : ownApplications.some(item => item.persona === 'WEALTH_MANAGER') ? 'Continue your customer organisation application.' : 'Choose the capacity you want to apply for.'}</h2><p>Your applicant records and operating assignments are separate. Customer admission does not grant a platform role or permission to create products.</p><Link href={href('/portal/onboarding')} className={styles.button}>Continue onboarding<ArrowRight aria-hidden="true" /></Link></div></section><Panel title="Your onboarding" action={<Link href={href('/portal/onboarding')} className={styles.textLink}>View application</Link>}>{ownApplications.length ? ownApplications.map(application => <div key={application.id}><DetailList rows={[{ label: application.persona === 'INVESTOR' ? 'Investor relationship' : 'Customer organisation relationship', value: <StatusBadge status={application.status} /> }, { label: 'Review expiry', value: dateLabel(application.approved_until) }, ...(application.persona === 'WEALTH_MANAGER' ? [{ label: 'Next owner', value: application.status === 'APPROVED' ? 'BlockXOne mandate reviewer and authorised role administrator' : application.status === 'SUBMITTED' ? 'BlockXOne independent compliance reviewer' : 'Applicant' }] : [])]} /></div>) : <EmptyState title="Introduce yourself" description="Submit your own applicant details and evidence for an independent review." href={href('/portal/onboarding')} action="Start onboarding" />}</Panel>{canInvest ? investorWork() : null}</div>
  }

  return <PortalCommandProvider snapshot={snapshot} operatingContext={operatingContext} environment={release?.environment}><PortalShell user={data.user} organisationName={scope?.organisationName ?? organisations[0]?.name} capabilities={capabilities} active={config.active} title={title} description={config.description} eyebrow={config.eyebrow} breadcrumbs={breadcrumbs} release={release} operatingContext={operatingContext} actions={<a href={href(view, id)} className={styles.buttonSecondary}>Refresh saved state</a>}>
    {scopes?.length ? <nav aria-label="Assigned role and organisation" className={`${styles.scopeSelector} ${styles.sectionGap}`}>
      {scope ? <p>Working as <strong>{getRoleDashboard(scope.role)?.title ?? scope.role}</strong> in <strong>{scope.organisationName}</strong></p> : <p>Working with your <strong>personal and applicant relationships</strong>. An approved product-owner relationship here does not grant a native organisation role.</p>}
      <div className={styles.actions}><Link href={portalScopeHref('/portal', APPLICANT_CONTEXT)} className={styles.buttonSecondary} aria-current={operatingContext?.mode === 'APPLICANT' ? 'page' : undefined}>My personal / applicant relationships</Link>{scopes.map(item => <Link key={`${item.organisationId}-${item.role}`} href={portalScopeHref('/portal', { mode: 'ROLE', organisationId: item.organisationId, role: item.role })} className={styles.buttonSecondary} aria-current={item.organisationId === scope?.organisationId && item.role === scope?.role ? 'page' : undefined}>{item.organisationName} · {getRoleDashboard(item.role)?.title ?? item.role}</Link>)}</div>
    </nav> : null}
    <div className={styles.stack}>{content()}<RoleHelp operatingContext={operatingContext} /></div>
  </PortalShell></PortalCommandProvider>
}
