'use client'

import { useState } from 'react'
import Link from 'next/link'
import { ArrowRight, Building2, Layers3, Plus } from 'lucide-react'
import type { PortalPageData, PortalPath, PortalProduct, PortalSnapshot } from '@/lib/portal/contracts'
import { OnboardingForm } from './onboarding-form'
import { PortalCommandProvider } from './portal-client'
import { ProductForm } from './product-form'
import { PortalShell, type PortalNavigationKey } from './portal-shell'
import { DetailList, EmptyState, Notice, Panel, Statistic, StatusBadge, dateLabel, money } from './portal-primitives'
import { ApplicationReview, OfferingDocuments, ProductActions, ProductFacts, ProductNarrative, ProductReview, SubscriptionCancel, SubscriptionForm, currentInvestorApplication } from './portal-workflows'
import styles from './portal.module.css'

export function productManagementOrganisations(snapshot: PortalSnapshot) {
  return snapshot.organisations.filter(org => org.status === 'ACTIVE' && org.roles.some(role => ['IssuerFundManager', 'OfferingManager'].includes(role)))
}
function ProductCard({ product }: { product: PortalProduct }) {
  return <article className={styles.productCard}><div className={styles.productVisual} data-kind={product.terms.asset_type}>{product.terms.asset_type === 'FUND' ? <Layers3 aria-hidden="true" /> : <Building2 aria-hidden="true" />}<p>{product.terms.asset_type === 'FUND' ? 'Investment fund' : 'Real-estate investment'} · Fictional product</p></div><div className={styles.productCardBody}><h2>{product.terms.name}</h2><p>{product.terms.summary}</p><DetailList rows={[{ label: 'Unit price', value: money(product.terms.unit_price_minor) }, { label: 'Minimum investment', value: money((BigInt(product.terms.minimum_units) * BigInt(product.terms.unit_price_minor)).toString()) }, { label: 'Share class', value: product.terms.share_class }]} /><div className={styles.productCardFoot}><StatusBadge status={product.status} /><Link href={`/portal/opportunities/detail?id=${encodeURIComponent(product.id)}`} className={styles.textLink}>View opportunity <span aria-hidden="true">↗</span></Link></div></div></article>
}

const PAGE: Record<PortalPath, { title: string; eyebrow: string; description: string; active: PortalNavigationKey }> = {
  '/portal': { title: 'Your investment workspace.', eyebrow: 'Welcome to BlockXOne', description: 'Manage your relationship, products and investment instructions in one connected workspace.', active: 'overview' },
  '/portal/onboarding': { title: 'Start with your identity.', eyebrow: 'Client onboarding', description: 'Apply as an investor or wealth manager. Your information, evidence and review decision stay connected.', active: 'onboarding' },
  '/portal/products': { title: 'Products & offerings.', eyebrow: 'Wealth management', description: 'Structure a fund or real-estate investment, prepare its terms and move the offering through independent review.', active: 'products' },
  '/portal/products/new': { title: 'Structure a new product.', eyebrow: 'Wealth management / new product', description: 'Define the issuer, asset, economics and investor disclosures before submitting a single version for review.', active: 'products' },
  '/portal/products/detail': { title: 'Product workspace.', eyebrow: 'Wealth management / product', description: 'The saved terms, independent review and publication state for this product.', active: 'products' },
  '/portal/compliance': { title: 'Review with context.', eyebrow: 'Compliance work queue', description: 'Review applicant evidence and offering terms using your assigned authority. Your own submissions require another reviewer.', active: 'compliance' },
  '/portal/compliance/detail': { title: 'Review case.', eyebrow: 'Compliance / case review', description: 'Read the source evidence and record a reasoned decision against the current revision.', active: 'compliance' },
  '/portal/opportunities': { title: 'Explore investment opportunities.', eyebrow: 'Investor marketplace', description: 'Read published product terms and disclosures before deciding whether to submit a test subscription.', active: 'opportunities' },
  '/portal/opportunities/detail': { title: 'Investment opportunity.', eyebrow: 'Investor marketplace / offering', description: 'Review the mandate, unit economics, eligibility rules and exact offering documents.', active: 'opportunities' },
  '/portal/portfolio': { title: 'Your investment instructions.', eyebrow: 'My portfolio', description: 'Track your subscriptions from terms acceptance onward. A reservation is shown separately from funded, issued ownership.', active: 'portfolio' },
}

export function PortalScreen({ data, view, id }: { data: PortalPageData; view: PortalPath; id?: string }) {
  const [snapshot, setSnapshot] = useState(data.snapshot)
  const organisations = productManagementOrganisations(snapshot)
  const capabilities = { manageProducts: organisations.length > 0, reviewCompliance: snapshot.actor.can_review, invest: true }
  const ownApplications = snapshot.applications.filter(item => item.user_id === snapshot.actor.id)
  const ownSubscriptions = snapshot.subscriptions.filter(item => item.investor_id === snapshot.actor.id)
  const managedProducts = snapshot.products.filter(product => organisations.some(org => org.id === product.organisation_id))
  const published = snapshot.products.filter(product => product.status === 'PUBLISHED')
  const selected = id ? snapshot.products.find(product => product.id === id && (view !== '/portal/opportunities/detail' || product.status === 'PUBLISHED')) : undefined
  const selectedApplication = id && snapshot.actor.can_review ? snapshot.applications.find(application => application.id === id) : undefined
  const config = PAGE[view]
  const title = selected && ['/portal/products/detail', '/portal/opportunities/detail'].includes(view) ? selected.terms.name : selectedApplication && view === '/portal/compliance/detail' ? selectedApplication.details.full_name : config.title
  const breadcrumbs = view === '/portal' ? [] : [{ label: config.active === 'products' ? 'Products & offerings' : config.active === 'compliance' ? 'Compliance' : config.active === 'opportunities' ? 'Opportunities' : config.active === 'portfolio' ? 'My portfolio' : 'My onboarding', href: view.includes('/detail') || view.endsWith('/new') ? config.active === 'products' ? '/portal/products' : config.active === 'compliance' ? '/portal/compliance' : '/portal/opportunities' : undefined }, ...(view.includes('/detail') ? [{ label: selected?.terms.name || selectedApplication?.details.full_name || 'Details' }] : view.endsWith('/new') ? [{ label: 'New product' }] : [])]
  function notFound() { return <Panel title="Record unavailable"><EmptyState title="This record is not available to your account" description="It may have changed or belong to another organisation. No access is granted by a shared URL." href="/portal" action="Return to overview" /></Panel> }
  function content() {
    if (view === '/portal/onboarding') return <OnboardingForm applications={ownApplications} onSaved={setSnapshot} />
    if (view === '/portal/products/new') return capabilities.manageProducts ? <ProductForm organisations={organisations} onSaved={setSnapshot} /> : <Panel title="Product access"><EmptyState title="An approved wealth-manager relationship is required" description="Complete the application and independent review. Your account will only see product controls for organisations where you are authorised." href="/portal/onboarding" action="Open my onboarding" /></Panel>
    if (view === '/portal/products') return <><div className={styles.statGrid}><Statistic label="Products in your scope" value={managedProducts.length} hint="Current organisation access" /><Statistic label="Awaiting review" value={managedProducts.filter(product => product.status === 'IN_REVIEW').length} hint="Independent decision required" /><Statistic label="Published offerings" value={managedProducts.filter(product => product.status === 'PUBLISHED').length} hint="Published test terms" /></div><Panel title="Product register" description="A single record connects each product to its organisation and document version." flush>{managedProducts.length ? <div className={styles.tableWrap}><table className={styles.table}><thead><tr><th scope="col">Product</th><th scope="col">Template</th><th scope="col">Version</th><th scope="col">Status</th><th scope="col">Workspace</th></tr></thead><tbody>{managedProducts.map(product => <tr key={product.id}><td><strong>{product.terms.name}</strong><small>{product.terms.issuer_name}</small></td><td>{product.terms.asset_type === 'FUND' ? 'Fund' : 'Real estate'}</td><td>Revision {product.revision}</td><td><StatusBadge status={product.status} /></td><td><Link href={`/portal/products/detail?id=${product.id}`}>Open product</Link></td></tr>)}</tbody></table></div> : <EmptyState title={capabilities.manageProducts ? 'Build your first offering' : 'No product-management access yet'} description={capabilities.manageProducts ? 'Start with the fund or real-estate template. Your draft stays private until its terms have been independently reviewed and published.' : 'An approved wealth-manager application and a scoped organisation role are required to manage products.'} href={capabilities.manageProducts ? '/portal/products/new' : '/portal/onboarding'} action={capabilities.manageProducts ? 'Create a product' : 'Apply as a wealth manager'} />}</Panel></>
    if (view === '/portal/products/detail') {
      if (!selected) return notFound()
      const canManage = organisations.some(org => org.id === selected.organisation_id)
      return <div className={styles.stack}><div className={styles.wideGrid}><div className={styles.stack}><ProductFacts product={selected} /><ProductNarrative product={selected} /><OfferingDocuments product={selected} /></div>{canManage ? <ProductActions product={selected} onSaved={setSnapshot} /> : <Notice title="Read-only product access">Your account has no product-management mandate for this organisation.</Notice>}</div>{canManage && ['DRAFT', 'CHANGES_REQUIRED'].includes(selected.status) ? <ProductForm key={`${selected.id}-${selected.revision}`} organisations={organisations} product={selected} onSaved={setSnapshot} /> : null}</div>
    }
    if (view === '/portal/compliance') {
      if (!snapshot.actor.can_review) return <Panel title="Review access"><EmptyState title="This account is not a compliance reviewer" description="Review authority is assigned by the backend. Completing an application or creating a product does not grant it." href="/portal" action="Return to overview" /></Panel>
      const applications = snapshot.applications.filter(item => item.status === 'SUBMITTED')
      const products = snapshot.products.filter(item => item.status === 'IN_REVIEW')
      return <><div className={styles.statGrid}><Statistic label="Client applications" value={applications.length} hint="Submitted evidence packages" /><Statistic label="Offering reviews" value={products.length} hint="Versioned product terms" /><Statistic label="Review provider" value="Manual" hint="Test mode · no vendor KYC claim" /></div><Panel title="Work queue" description="Every decision is bound to the current case version." flush>{applications.length || products.length ? <div className={styles.tableWrap}><table className={styles.table}><thead><tr><th scope="col">Case</th><th scope="col">Review type</th><th scope="col">Version</th><th scope="col">Independence</th><th scope="col">Action</th></tr></thead><tbody>{applications.map(application => <tr key={application.id}><td><strong>{application.details.full_name}</strong><small>Submitted {dateLabel(application.submitted_at)}</small></td><td>{application.persona === 'INVESTOR' ? 'Investor onboarding' : 'Wealth-manager onboarding'}</td><td>{application.revision}</td><td>{application.user_id === snapshot.actor.id ? 'Another reviewer required' : 'Separate applicant'}</td><td><Link href={`/portal/compliance/detail?id=${application.id}`}>Review case</Link></td></tr>)}{products.map(product => <tr key={product.id}><td><strong>{product.terms.name}</strong><small>{product.terms.issuer_name}</small></td><td>Offering review</td><td>{product.revision}</td><td>{product.created_by === snapshot.actor.id ? 'Another reviewer required' : 'Separate creator'}</td><td><Link href={`/portal/compliance/detail?id=${product.id}`}>Review offering</Link></td></tr>)}</tbody></table></div> : <EmptyState title="No cases are waiting for review" description="Submitted client applications and product disclosures will appear here. Nothing is approved automatically." />}</Panel></>
    }
    if (view === '/portal/compliance/detail') {
      if (!snapshot.actor.can_review) return notFound()
      return selectedApplication ? <ApplicationReview key={`${selectedApplication.id}-${selectedApplication.revision}`} application={selectedApplication} snapshot={snapshot} onSaved={setSnapshot} /> : selected ? <ProductReview key={`${selected.id}-${selected.revision}`} product={selected} snapshot={snapshot} onSaved={setSnapshot} /> : notFound()
    }
    if (view === '/portal/opportunities') return <div className={styles.stack}><Notice title="Read before you subscribe">Only published test offerings are displayed. A current investor approval and matching eligibility are required to submit a subscription. No returns or liquidity are guaranteed.</Notice>{published.length ? <div className={styles.productGrid}>{published.map(product => <ProductCard key={product.id} product={product} />)}</div> : <Panel title="Published opportunities"><EmptyState title={currentInvestorApplication(snapshot) ? 'No published offerings are available to your account' : 'Prepare your investor access'} description={currentInvestorApplication(snapshot) ? 'An authorised wealth manager must create a product, obtain an independent review and publish its approved version before it can appear here.' : 'Complete your investor application and obtain a current independent approval. Published offerings remain subject to the country and investor-classification rules that apply to your account.'} href="/portal/onboarding" action="Open my investor onboarding" /></Panel>}</div>
    if (view === '/portal/opportunities/detail') return selected?.status === 'PUBLISHED' ? <div className={styles.wideGrid}><div className={styles.stack}><Notice title="Fictional test offering">{selected.terms.summary}</Notice><ProductFacts product={selected} /><ProductNarrative product={selected} /><OfferingDocuments product={selected} /></div><SubscriptionForm product={selected} snapshot={snapshot} onSaved={setSnapshot} /></div> : notFound()
    if (view === '/portal/portfolio') {
      const pending = ownSubscriptions.filter(subscription => subscription.status === 'AWAITING_FUNDING')
      const amount = pending.reduce((sum, subscription) => sum + BigInt(subscription.amount_minor), 0n).toString()
      return <div className={styles.stack}><div className={styles.statGrid}><Statistic label="Subscription instructions" value={ownSubscriptions.length} hint="Your saved instructions" /><Statistic label="Awaiting funding" value={pending.length} hint="Reserved, not issued" /><Statistic label="Unfunded test obligations" value={money(amount)} hint="Not cash or asset value" /></div><Notice title="Reservations are not holdings">This view lists accepted subscriptions and their funding obligations. No token holding or performance balance is manufactured from a reservation.</Notice><Panel title="Your subscriptions" description="Each instruction references its accepted product revision and terms hash." flush>{ownSubscriptions.length ? <div className={styles.tableWrap}><table className={styles.table}><thead><tr><th scope="col">Product</th><th scope="col">Units</th><th scope="col">Instruction value</th><th scope="col">Status</th><th scope="col">Action</th></tr></thead><tbody>{ownSubscriptions.map(subscription => <tr key={subscription.id}><td><strong>{subscription.product_name}</strong><small>Terms revision {subscription.product_revision} · {dateLabel(subscription.created_at)}</small></td><td>{subscription.units}</td><td>{money(subscription.amount_minor)}</td><td><StatusBadge status={subscription.status} /></td><td>{subscription.status === 'AWAITING_FUNDING' ? <SubscriptionCancel id={subscription.id} onSaved={setSnapshot} /> : <span className={styles.muted}>No pending action</span>}</td></tr>)}</tbody></table></div> : <EmptyState title="Your investment journey starts here" description="Once you accept a published offering’s terms, the saved subscription appears here with its true funding and ownership state." href="/portal/opportunities" action="Explore opportunities" />}</Panel></div>
    }
    const investor = currentInvestorApplication(snapshot)
    return <><section className={styles.hero}><div><p className={styles.eyebrow}>Your next chapter in ownership</p><h2>{capabilities.manageProducts ? 'Bring a product to market. Keep every decision connected.' : investor ? 'Explore the terms. Make an informed instruction.' : 'A clear path from onboarding to ownership.'}</h2><p>{capabilities.manageProducts ? 'Structure multi-asset products with scoped issuer access, versioned disclosures and independent review.' : 'Start with a personal application, review published opportunities and track each instruction through its real recorded state.'}</p><Link href={capabilities.manageProducts ? '/portal/products' : investor ? '/portal/opportunities' : '/portal/onboarding'} className={styles.button}>{capabilities.manageProducts ? 'Open product workspace' : investor ? 'Explore opportunities' : 'Continue onboarding'}<ArrowRight aria-hidden="true" /></Link></div><div className={styles.heroAside}><dl><dt>Your relationship</dt><dd>{capabilities.manageProducts ? 'Product management enabled' : investor ? 'Test investor approved' : 'Onboarding required'}</dd></dl><dl><dt>Environment</dt><dd>Hosted · Fictional test data</dd></dl><dl><dt>Authority</dt><dd>Individual login · Scoped access</dd></dl></div></section><div className={styles.statGrid}><Statistic label="Your applications" value={ownApplications.length} hint="Investor and wealth-manager relationships" /><Statistic label="Published opportunities" value={published.length} hint="Available test offering versions" /><Statistic label="Your instructions" value={ownSubscriptions.length} hint="Subscriptions, not fabricated holdings" /></div><div className={styles.grid}><Panel title="Your onboarding" action={<Link href="/portal/onboarding" className={styles.textLink}>View application</Link>}>{ownApplications.length ? ownApplications.map(application => <div key={application.id}><DetailList rows={[{ label: application.persona === 'INVESTOR' ? 'Investor relationship' : 'Wealth-manager relationship', value: <StatusBadge status={application.status} /> }, { label: 'Review expiry', value: dateLabel(application.approved_until) }]} /></div>) : <EmptyState title="Introduce yourself" description="A short application connects your identity, supporting evidence and intended relationship to a recorded review decision." href="/portal/onboarding" action="Start onboarding" />}</Panel><Panel title="Recent recorded activity" description="Events from your accessible hosted records.">{snapshot.events.length ? <ol className={styles.timeline}>{snapshot.events.slice(0, 5).map(event => <li key={event.id}><strong>{event.summary || event.kind.replaceAll('_', ' ')}</strong><p>{dateLabel(event.created_at)}</p></li>)}</ol> : <EmptyState title="Your activity will appear here" description="Submitted applications, offering changes and subscription instructions create an activity record. No simulated history is shown." />}</Panel></div></>
  }
  return <PortalCommandProvider snapshot={snapshot}><PortalShell user={data.user} organisationName={snapshot.organisations[0]?.name} capabilities={capabilities} active={config.active} title={title} description={config.description} eyebrow={config.eyebrow} breadcrumbs={breadcrumbs} actions={view === '/portal/products' && capabilities.manageProducts ? <Link href="/portal/products/new" className={styles.button}><Plus aria-hidden="true" />Create a product</Link> : <a href={`${view}${id ? `?id=${encodeURIComponent(id)}` : ''}`} className={styles.buttonSecondary}>Refresh saved state</a>}>{content()}</PortalShell></PortalCommandProvider>
}
